### ISSUE TITLE
bbs/v1 schema returned 404

### ISSUE THREAD

**Issue by suutaku** [w3c-ccg/vc-di-bbs#71]
`https://w3id.org/security/bbs/v1` returned `404`  today.  that's a big problem.

**Comment by vongohren** [comment]
Absolutely! Just giving you a way our right now and this is an active issue

**Comment by swcurran** [comment]
The cause of the 404 is that the specification was renamed, with a new URL.  The problem is that the rename broke the redirection from: https://w3id.org/security/bbs/v1 (which is used in all BBS+ VCs AFAIK) to https://w3c-ccg.github.io/ldp-bbs2020/contexts/v1/.

The redirection needs to be updated to point to: https://w3c-ccg.github.io/vc-di-bbs/contexts/v1/

I'm trying to find out how to do that.

By the way, caching doesn't help when you are running tests or creating tutorials that reference the context. If the intention was to change the link (which I don't think it was), there should more guidance given.

**Comment by tplooker** [comment]
This issue has now been resolved, it was caused by a repository rename in preparation for this to be adopted as a work item of the VC WG.

**Comment by swcurran** [comment]
Thanks.
